name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: CTS-Save-Editor-windows
            artifact_path: dist/CTS-Save-Editor.exe

          - os: ubuntu-latest
            artifact_name: CTS-Save-Editor-linux
            artifact_path: dist/CTS-Save-Editor

          - os: macos-latest
            artifact_name: CTS-Save-Editor-macos-arm64
            artifact_path: dist/CTS-Save-Editor.app

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Install dependencies
        run: uv sync --dev

      - name: Install UPX on Windows
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-upx@v4
        with:
          version: latest
          install-only: true

      - name: Build
        run: uv run python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
